/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan.umk;

/**
 *
 * @author ASUS
 */
public class penjualan extends javax.swing.JFrame {

    /**
     * Creates new form penjualan
     */
    public penjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbarang = new javax.swing.JComboBox<>();
        txtharga = new javax.swing.JTextField();
        txtbeli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        cmdbayar = new javax.swing.JButton();
        cmdbatal = new javax.swing.JButton();
        cmdkeluar = new javax.swing.JButton();
        cmdjumlah = new javax.swing.JButton();
        txttransaksi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Aplikasi Penjualan");

        jLabel2.setText("No Transaksi");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Harga barang");

        jLabel5.setText("Jumlah Beli");

        cbbarang.setName("cbbarang"); // NOI18N
        cbbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbarangMouseClicked(evt);
            }
        });

        txtharga.setName("txtharga"); // NOI18N

        txtbeli.setName("txtbeli"); // NOI18N

        jLabel6.setText("Jumlah Bayar");

        txtbayar.setName("txtbayar"); // NOI18N

        cmdbayar.setText("BAYAR");
        cmdbayar.setName("cmdbayar"); // NOI18N
        cmdbayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdbayarMouseClicked(evt);
            }
        });

        cmdbatal.setText("BATAL");
        cmdbatal.setName("cmdbatal"); // NOI18N
        cmdbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdbatalMouseClicked(evt);
            }
        });

        cmdkeluar.setText("KELUAR");
        cmdkeluar.setName("cmdkeluar"); // NOI18N

        cmdjumlah.setText("HITUNG JUMLAH BARANG");
        cmdjumlah.setName("cmdjumlah"); // NOI18N
        cmdjumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdjumlahMouseClicked(evt);
            }
        });

        txttransaksi.setName("txttransaksi"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbarang, 0, 164, Short.MAX_VALUE)
                            .addComponent(txtharga)
                            .addComponent(txtbeli)
                            .addComponent(txtbayar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdjumlah)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdkeluar)
                            .addComponent(cmdbatal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmdbayar)
                        .addGap(61, 61, 61)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txttransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdbatal))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdkeluar))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdjumlah))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdbayar)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdbatalMouseClicked
        // TODO add your handling code here:
        harga_barang.setText("");
        no_transaksi.settext("");
        jumlah_beli.setText("");
        jumlah_barang.setText("");
        nama_barang.setSelectedIndex(0);
        
    }//GEN-LAST:event_cmdbatalMouseClicked

    private void cmdjumlahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdjumlahMouseClicked
        // TODO add your handling code here:
        int JumlahBarang=Integer.parseInt(jumlah_beli.getText());
        int HargaBarang=Integer.parseInt(harga_barang.getText());
        jumlah_harga.setText(Integer.toString(HargaBarang*JumlahBarang));
    }//GEN-LAST:event_cmdjumlahMouseClicked

    private void cmdbayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdbayarMouseClicked
        // TODO add your handling code here:
        int JumlahBayar=Integer.parseInt(jumlah_bayar.getText());
        int JumlahHarga=Integer.parseInt(jumlah_harga.getText());
        if (JumlahBayar>=JumlahHarga){
        jumlah_kembalian.setText(Integer.toString(JumlahBayar-JumlahHarga));
}
        else {
        jumlah_kembalian.setText("Uang Anda Kurang");
}
    }//GEN-LAST:event_cmdbayarMouseClicked

    private void cbbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbarangMouseClicked
        // TODO add your handling code here:
    String NamaBarang=(String)nama_barang.getSelectedItem();
    switch (NamaBarang){
    case "Televisi":
    harga_barang.setText("3000000");
    break;
    case "Komputer":
    harga_barang.setText("4000000");
    break;
    case "Laptop":
    harga_barang.setText("5000000");
    break;
    case "Dispenser":
    harga_barang.setText("1000000");
    break;
    case "Kompor":
    harga_barang.setText("500000");
    break;
    }//GEN-LAST:event_cbbarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbarang;
    private javax.swing.JButton cmdbatal;
    private javax.swing.JButton cmdbayar;
    private javax.swing.JButton cmdjumlah;
    private javax.swing.JButton cmdkeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtbeli;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txttransaksi;
    // End of variables declaration//GEN-END:variables
}
